### ISSUE TITLE
ReadPreference and slaveOk

### ISSUE THREAD

**Issue by vlechemin** [mongodb-labs/mongo-php-library-prototype#38]
While setting read preference on a secondary, i get this error: not master and slaveOk=false.
But I can't find how to set it with the driver.
Thanks!

**Comment by bjori** [comment]
Can you paste an example code that results in this behavior?

We are aware of one case where this happened which is fixed now; https://jira.mongodb.org/browse/PHPC-441
But that case should be very bleeding edgecase you should never experience in an normal usage of the driver.

**Comment by vlechemin** [comment]
Thanks, I recompiled from master and it seems that it has been solved by this fix.
But I don't think it was an edge case.
the read preference used: new ReadPreference(ReadPreference::RP_NEAREST, [])
and the query was just a basic find([])

**Comment by bjori** [comment]
Interesting.
Were you connecting to a secondary directly? (e.g. not provding the "replicaSet=name" option to the uri?)

I guess we underestimated the impact of this issue :/

**Comment by vlechemin** [comment]
It was not in the uri, but in the options of the Client (2nd argument).

**Comment by bjori** [comment]
Can you post the actual line you constructed the Manager with?

It may have been a different bug.

**Comment by jmikola** [comment]
> recompiled from master

@vlechemin: Additionally, can you tell us what versions of the extension (actual release) and this library (commit hash would be fine) you were using?

I assume you were on 1.0.0beta2 of the extension, as there shouldn't be anything its master branch that would have affected read preference application unless this was actually an issue with the underlying C driver (we recently bumped things from 1.2.0rc0 to 1.2.0 final).

**Comment by jmikola** [comment]
On second thought, this might have been [PHPC-441](https://jira.mongodb.org/browse/PHPC-441), which was resolved with bumping the C driver to 1.2.0 final (and currently only in the extension's master branch). PHPLIB makes heavy use of these hinted queries, since we do server selection manually and then execute commands, queries, and writes directly on Server objects (instead of through the Manager).

**Comment by vlechemin** [comment]
@bjori, it was with the wrapper provided by the php lib:
```
new MongoDB\Client('mongodb://host1,host2/dbname', [
    'replicaSet' => 'rsName',
    'username' => 'user',
    'password' => 'pwd',
])
```
hi @jmikola, it was the beta1 from this archive: https://s3.amazonaws.com/drivers.mongodb.org/hhvm/hhvm-mongodb-1.0beta1.tgz
and the version of the lib is: fbb10fec3c423d306a76e0915688c09e0272547f

**Comment by jmikola** [comment]
@vlechemin: Thanks for confirming. The bump to libmongoc 1.2.0 was done after the HHVM driver's 1.0.0-beta1 release (see [changelog](https://github.com/mongodb-labs/mongo-hhvm-driver-prototype/compare/1.0beta1...master)). If you're willing to recompile its master branch and confirm that it solves the issue, that'd be appreciated. Otherwise, we should have a new HHVM tag cut later in the week for you to test with.

**Comment by vlechemin** [comment]
I think I misunderstood when you asked about the hash, the one for the driver is a89194261edbd1eb3fdb8cbf808a767866b29403 and had the commit about libmongoc 1.2.0.
Everything is working fine now, thank you

**Comment by jmikola** [comment]
:+1:
